name = "Capulong Halal"
license = "MIT"
description = "Custom theme for Capulong Farms Halal Division"
homepage = "https://halal.capulongfarms.org/"
tags = ["farm", "ecommerce", "halal", "certified", "fresh", "organic", "islamic"]
features = ["responsive"]
min_version = "0.120.0"
